### ISSUE TITLE
Consider using loki for log ingest and tempo for traces

### ISSUE THREAD

**Issue by highb** [observeinc/manifests#20]
Considering that you are now using the `grafana-agent` for metrics, have you considered making use of the other features in that agent for logs and traces, as well? That would reduce the number of external dependencies that you have to consider and make maintenance/config for users much more straightforward.

**Comment by NathanNam** [comment]
@highb Sorry for the delayed response. Thanks for your suggestion. In general, the fewer agents customers need to install, the better experience they will have. However, we are not sure at this moment whether ``grafana-agent`` covers everything we need for logs and traces.
